/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/commandes': typeof CommandesRoute
  '/panier': typeof PanierRoute
  '/profil': typeof ProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/commandes': typeof CommandesRoute
  '/panier': typeof PanierRoute
  '/profil': typeof ProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/commandes': typeof CommandesRoute
  '/panier': typeof PanierRoute
  '/profil': typeof ProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/categories' | '/commandes' | '/panier' | '/profil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categories' | '/commandes' | '/panier' | '/profil'
  id: '__root__' | '/' | '/categories' | '/commandes' | '/panier' | '/profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  CommandesRoute: typeof CommandesRoute
  PanierRoute: typeof PanierRoute
  ProfilRoute: typeof ProfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  CommandesRoute: CommandesRoute,
  PanierRoute: PanierRoute,
  ProfilRoute: ProfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
